name: Overbård Multi Repo CI - Post Build Action
description: Used in the generated workflow to do the steps after doing the build
inputs:
  component:
    description: The name of the component being built
    required: true
  build:
    description: Indicates if we are a doing a component build or not. 1 means we are, 0 means we are not (i.e. it is a test job for a custom component).
    required: true
  custom:
    description: Indicates if this is a custom component or not. 1 means we are, 0 means we are not.
    required: true
  snapshots:
    description: A tar.gz containing the SNAPSHOTS from the job

runs:
  using: 'docker'
  image: 'Dockerfile'
